### ISSUE TITLE
使用的python版本

### ISSUE THREAD

**Issue by GuiltyInori** [kongds/scaling_sentemb#1]
请问项目使用的python是哪个版本？我使用python3.10安装项目环境，出现了许多错误

**Comment by kongds** [comment]
我试了一下应该是3.10和scipy版本不兼容（我用的是Python 3.9.16 ），  去掉requirement里的scipy版本要求应该就可以

**Comment by GuiltyInori** [comment]
> 我试了一下应该是3.10和scipy版本不兼容（我用的是Python 3.9.16 ）， 去掉requirement里的scipy版本要求应该就可以

感谢回复，我将scipy改到了1.11.1，bitsandbytest=0.37.2后就没问题了。
