### ISSUE TITLE
About the usage of your prompt.

### ISSUE THREAD

**Issue by only-changer** [kongds/scaling_sentemb#14]
Hi, I am interested in the prompt proposed in your paper to get sentence embeddings.
I wonder if I can directly use your prompt in other open-source LLM, e.g. LLAMA 3, to get meaningful sentence embeddings?

For example, using this code to get the sentence embedding of "input_text", via the open-source LLAMA 3 without using the training part of your paper.

tokenizer = AutoTokenizer.from_pretrained(model_id)
model = LlamaModel.from_pretrained(model_id,)
prompt_template = 'This sentence: "{text}" means in one word:'
text = prompt_template.format(text=input_text)
t_input = tokenizer(text, return_tensors="pt").to(device)
last_hidden_state = model(**t_input, output_hidden_states=True, return_dict=True).hidden_states[-1].cpu()

Thank you.

**Comment by kongds** [comment]
Yes, you can also test sentence embeddings with our prompt on LLaMA3 using the following scripts:
```sh
MODEL_PATH="meta-llama/Meta-Llama-3-8B"
TEMPLATE='This_sentence_:_"*sent_0*"_means_in_one_word:"'
python evaluation.py \
    --model_name_or_path   $MODEL_PATH \
    --mode test --mask_embedding_sentence \
    --mask_embedding_sentence_template $TEMPLATE --load_kbit 16

```
This will give the following results: 
<img width="673" alt="image" src="https://github.com/kongds/scaling_sentemb/assets/19282154/b5af3b99-452d-4d86-a920-5da9cdfd5fee">

**Comment by mariateleki** [comment]
@only-changer Just a heads up, you are missing a " from the end of the prompt_template string you provided -- see page 4 of their paper for why they include this (they said it helps to prevent punctuation generation).
