### ISSUE TITLE
Maybe errors in pre-print paper

### ISSUE THREAD

**Issue by YuboFeng2023** [kongds/scaling_sentemb#3]
Dear author,

What a fabulous sentence embedding model you have created!
But there are show error(s) that need to be corrected in pre-print paper:
1. Temperature of contrastive learning. In your paper, the temperature is claimed to be 0.5, but I found it should be 0.05 according to your code. All in all, which one is correct?

Best wishes!

**Comment by kongds** [comment]
Thank you for your advice. The temperature of contrastive learning should be 0.05. I will correct this error in the next version of the paper.
