### ISSUE TITLE
Maybe there are errors in your tokenization

### ISSUE THREAD

**Issue by YuboFeng2023** [kongds/scaling_sentemb#4]
Hi!

What a fabulous sentence embedding model you have created!
But there may be bugs in your code:

The sentences:

```python
['hello', 'hello hello hello']
```

After encode and decode by your **OPT** tokenizer, the sentences become:

```text
<s><s><s></s>Hello
</s>Hello Word Hello Word
```

**LOOK!** there are eos_token, <\/s>, at the beginning of sentence.
This is inconsistent with our usual understanding of tokenization.
I think the correct tokenization should be:

```text
<s><s><s><s>Hello
<s>Hello Word Hello Word
```

Can you provide some guidance on this setting?

**Comment by kongds** [comment]
This is not bug.
For opt tokenizer, it uses same token id for bos_token and eos_token (`tokenizer.bos_token_id == tokenizer.eos_token_id == 2`)

**Comment by YuboFeng2023** [comment]
> This is not bug.
> For opt tokenizer, it uses same token id for bos_token and eos_token (`tokenizer.bos_token_id == tokenizer.eos_token_id == 2`)

Thank you for your reply, but this is really different from the conventional method. 
Cloud you please provide some evidence?

**Comment by kongds** [comment]
You can find it at https://huggingface.co/docs/transformers/model_doc/opt.
<img width="699" alt="image" src="https://github.com/kongds/scaling_sentemb/assets/19282154/07826d06-430d-4ff9-8fe2-356ea3591312">
<img width="677" alt="image" src="https://github.com/kongds/scaling_sentemb/assets/19282154/81b8ddda-c0b5-4180-b633-8efa7aa7ada2">

**Comment by YuboFeng2023** [comment]
> You can find it at https://huggingface.co/docs/transformers/model_doc/opt.
> <img alt="image" width="699" src="https://user-images.githubusercontent.com/19282154/269597285-07826d06-430d-4ff9-8fe2-356ea3591312.png">
> <img alt="image" width="677" src="https://user-images.githubusercontent.com/19282154/269597324-81b8ddda-c0b5-4180-b633-8efa7aa7ada2.png">

Thank you very much! This answer is very solid!
