### ISSUE TITLE
download_nli.sh  was not found when downloading data

### ISSUE THREAD

**Issue by fuxiaG** [kongds/scaling_sentemb#5]
Hi, @kongds! I can't find "download_nli.sh" when I downloaded data according to "readme.md". How can I get this file? Or can you please send it to my email (fuxia_guo@163.com or gfx1024697212@gmail.com)? Thank you!

**Comment by kongds** [comment]
Thank you for your advice.

We use the same file with SimCSE and PromptBERT.

This file can be found in
https://github.com/kongds/Prompt-BERT/blob/main/data/download_nli.sh. And we will add it later.

**Comment by kongds** [comment]
We add this in https://github.com/kongds/scaling_sentemb/commit/ba44c2620887eed01734b3f9a754a048eb70e76f .

**Comment by fuxiaG** [comment]
Thank you ver much!!!
















At 2023-09-23 13:30:35, "kongds" ***@***.***> wrote:

We add this in ba44c26 .
