### ISSUE TITLE
What causes the training of the model to be ineffective?

### ISSUE THREAD

**Issue by YuboFeng2023** [kongds/scaling_sentemb#6]
Hi.

What a fabulous sentence embedding model you have created!
I am trying to reproduce your "3.3 Contrastive learning with efficient fine-tuning" by using your **ft_llm.py** script.
And I keep the same parameters with your setting, OPT-1.3b, epoch=1, learning_rate=5e-4, etc......
But when I evaluate these generated checkpoints, **THE PERFORMANCE IS UNCHANGED!**
By other words, the training is invalid, because the generated checkpoints are invariant.

Could you please offer some advice for this problem? Thank you very much!

**Comment by kongds** [comment]
Can you provide training script and evaluation script?

**Comment by YuboFeng2023** [comment]
> Can you provide training script and evaluation script?

Sure, thank you very much for being willing to help me!

As mention above, the training script is totally based on your [ft_llm.py](https://github.com/kongds/scaling_sentemb/blob/main/ft_llm.py)

I think the root cause of the problem is "the loading method of base_model and lora_model", here is the code.

1. Loading LLM:

```python
base_model = AutoModelForCausalLM.from_pretrained(
            argv.llm,
            torch_dtype=torch.float16 if argv.fp16 else torch.float32,
            device_map=device,
        )
        # base_model.eval()
```

2. Loading Lora:

```python
peft_model = PeftModel.from_pretrained(
            model=base_model,
            model_id=argv.lora,
            torch_dtype=torch.float16 if argv.fp16 else torch.float32,
            device_map=device,
        )
```

3. Evaluating ...

**Comment by kongds** [comment]
If you train opt-1.3b with `CUDA_VISIBLE_DEVICES=0,1 bash train_llm.sh opt-1.3b`, you can find a directory `opt-1.3b-lora`, which contains checkpoints.

After training, you can run `bash eval_checkpoints.sh opt-1.3b-lora`, which will evaluate each checkpoint in STS-B valid set, and then test best checkpoint in STS benchmark.
