### ISSUE TITLE
opt-1.3b does not have a file config.json

### ISSUE THREAD

**Issue by JhonDan1999** [kongds/scaling_sentemb#7]
I am trying to use the model but it gave me this error 
![Screenshot 2023-10-01 at 7 00 26 PM](https://github.com/kongds/scaling_sentemb/assets/145554661/2165d4a6-e4f1-4198-bdb7-664f74a20e3a)
![Screenshot 2023-10-01 at 7 01 02 PM](https://github.com/kongds/scaling_sentemb/assets/145554661/4a9a32a0-2839-42e6-afff-c9fa83be2de9)

![Screenshot 2023-10-01 at 7 00 45 PM](https://github.com/kongds/scaling_sentemb/assets/145554661/75a64010-8117-45ac-a822-8297ec173ab8)

can you please help me with the correct way to use the model with huggingface

**Comment by kongds** [comment]
The models we uploaded are Parameter-Efficient Fine-Tuning (PEFT) checkpoints.

For example
To use prompted-opt-1.3b, you need load opt-1.3b first, and then load peft checkpoint over opt-1.3b

```python
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer
from peft import PeftModel

# Import our models. The package will take care of downloading the models automatically
tokenizer = AutoTokenizer.from_pretrained("facebook/opt-1.3b")
model = AutoModelForCausalLM.from_pretrained("facebook/opt-1.3b")
tokenizer.pad_token_id = 0 
tokenizer.padding_side = "left"
model = PeftModel.from_pretrained(model, "royokong/prompteol-opt-1.3b", torch_dtype=torch.float16)
```

**Comment by JhonDan1999** [comment]
thank you

**Comment by JhonDan1999** [comment]
.
