### ISSUE TITLE
Is it necessary to add </s>?

### ISSUE THREAD

**Issue by 545999961** [kongds/scaling_sentemb#8]
I noticed that the provided usage examples did not include </s>, and the last one '"' taken as the embedding. However, in the training files, '</s>' was included, and '</s>' was chosen as the embedding. Which one should be considered the primary choice?

**Comment by kongds** [comment]
Hello,
We also don't  add </s> on training and set `add_eos_token` to False in below:
https://github.com/kongds/scaling_sentemb/blob/8567aa083c1b3c77586670f91e7f78eb80694ad3/ft_llm.py#L390-L392

**Comment by 545999961** [comment]
Thanks for you help!
